version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
      - /app/__pycache__
    command: python debug_server.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3000
    depends_on:
      - backend

volumes:
  node_modules:
  python_cache: